static float mLightIntensityMin = 1.0;
static float mLightIntensityMax = 10.0;
static float mLightDistance = 1000;
static float mLightPlaneNear = 0.1;
static float mLightPlaneFar = 400.0;
static float mTemperature = 6600.0; // range 1000 ~ 40000 // Default value D66 used for pure white
static float mEnvLightIntensityMin = 1.0;
static float mEnvLightIntensityMax = 6.2831852;
static float mBloomIntensityMin = 1.0;
static float mBloomIntensityMax = 20.0;
static float mBloomGhostThresholdMax = 10.0;
static float mExposureMin = 2.0;
static float mExposureMax = 8.0;
static float mExposureEyeAdapationMin = 0.0;
static float mExposureEyeAdapationMax = 8.0;
static float mVignetteInner = 1.0;
static float mVignetteOuter = 3.5;
static float mPointLightNear = 1.0;
static float mPointLightFar  = 400.0;
static float mPSSMCascadeZMin = 5;
static float mPSSMCascadeZMax = 1500;
static float mPSSMCascadeLambda = 0.5;
static float mPSSMDepthZMin = 0;
static float mPSSMDepthZMax = 4000.0;
static float mSSRRangeMax = 1000.0;
static float mSSRRangeScale = 0.75;
static float mSSRThreshold = 1.0;
static float mSSRFadeStart = 0.8;
static float mGISaturation = 1.0;
static float mGIBlurSharpness = 2.0;
static float mSSGIScale = 1.5;
static float mSSGIIntensityDefault = 1.2;
static float mSSGIBiasDefault = 0.2;
static float mSSGIConeAngleDefault = 0.5;
static float mSSGIThicknessWeight = 0.35;
static float mSSSSIntensityMin = 0.04;
static float mSSSSIntensityMax = 0.02;
static float mSSDOParams[4] = {2.0, 2.0, 0.03, 0.15};
static float mSSDOBiasNear = 0.125;
static float mSSDOBiasFar = 0.0005;
static float mSSDOBiasFalloffNear = 20.0;
static float mSSDOIntensityMin = 2.4;
static float mSSDOIntensityMax = 10.0;
static float mSSDOBlurFalloff = 200.0;
static float mSSDOBlurSharpnessMin = 1.0;
static float mSSDOBlurSharpnessMax = 8.0;
static float mAmbientOcclusionMaxRadiusPixelPercentage = 0.1;
static float mAmbientOcclusionBilateralSharpness = 8.0;
static float mAmbientOcclusionBias = 0.2;
static float mFXAAQualitySubpix = 0.5;
static float mFXAAQualityEdgeThreshold = 0.166;
static float mFXAAQualityEdgeThresholdMin = 0.0333;
static float mSSRBlurMax = 512;
static float mSSRBlurMin = 4096;
static float mSSRBlurDefault = 1024;
static float mSSRBrightnessMin = 0.0;
static float mSSRBrightnessMax = 10.0;
static float mSSRBrightnessDefault = 3.0;
static float mSSROffsetMin = 0.05;
static float mSSROffsetMax = 2.0;
static float mSSROffsetDefault = 0.1;
static float mSSRThicknessMin = 0.01;
static float mSSRThicknessMax = 5.0;
static float mSSRThicknessDefault = 0.5;
static float mSSRFresnelMin = 1.0;
static float mSSRFresnelMax = 0.0;
static float mSSRFresnelDefault = 0.6;
static float mSSRSmoothnessMax = 2.0;
static float mSSRSmoothnessMin = -1.0;
static float mSSRSmoothnessDefault = 2.0;

static float mSensorWidth = 36.0f;