#define USE_CUSTOM_PARAMS 0
#define USE_RGB_COLORSPACE 0

static float3 TopColor = float3(1, 0, 1);
static float3 BottomColor = float3(1, 0, 1);
static float3 MediumColor = float3(1, 0, 1);

static float TopExponent = 4.0;
static float BottomExponent = 0.5;